name: CI
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint && pnpm tc
      - run: pnpm test